server:
  port: 8050
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/product
    username: gustavo
    password: gustavo
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  # Configuracoes do Flyway (controle de migracoes de banco de dados)
  flyway:
    # Cria baseline se o schema nao existir
    baseline-on-migrate: true
    # Habilita o Flyway
    enabled: true
    # Descricao da baseline
    baseline-description: "inicio"
    # Versao inicial da baseline de onde comeca
    baseline-version: 0
    # Usa as mesmas credenciais do datasource
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}






